#IMU data from firmware

builtin_interfaces/Time stamp

#gravity vector
float32 gravity_x
float32 gravity_y
float32 gravity_z

#orientation
float32 angular_x
float32 angular_y
float32 angular_z
float32 angular_w

#gyroscopic angular velocities
float32 gyro_roll
float32 gyro_pitch
float32 gyro_yaw

#linear acceleration
float32 accel_x
float32 accel_y
float32 accel_z

#magnetic field strength
float32 field_x
float32 field_y
float32 field_z



